sinjyu:
  id: 13
  idol_id: 13
  name:
    family: 晴海
    family_kana: ハルミ
    given: シンジュ
    given_kana: シンジュ
    shorten: シンジュ
  old: 10
  birthday: 8/28
  zodiac_signs: 乙女座
  blood_type: A型
  height: 134
  weight: 32
  bust: 71
  waist: 48
  hip: 70
  cv: 桑原 由気
  nickname: シンジュ、シィちゃん
  special_skill: 経理
  favorite_things: ['カエルグッズ集め']
  belongs: ['小学生']
  unit: ['777☆SISTERS','サンボンリボン']
