kyoko:
  id: 15
  idol_id: 15
  name:
    family: 上杉
    family_kana: ウエスギ
    given: ウエバス・キョーコ
    given_kana: ウエバス・キョーコ
    shorten: キョーコ
  old: 16
  birthday: 8/14
  zodiac_signs: しし座
  blood_type: B型
  height: 146
  weight: 45
  bust: 89
  waist: 55
  hip: 88
  cv: 吉井 彩実
  nickname: キョーコ
  special_skill: アンタにはあんの？
  favorite_things: ['ホラー映画、がキラい！']
  belongs: ['高校生']
  unit: ['Le☆S☆Ca']
