honoka:
  id: 20
  idol_id: 20
  name:
    family: 西園
    family_kana: ニシゾノ
    given: ホノカ
    given_kana: ホノカ
    shorten: ホノカ
  old: 17
  birthday: 5/28
  zodiac_signs: 双子座
  blood_type: O型
  height: 162
  weight: 48
  bust: 83
  waist: 56
  hip: 85
  cv: 植田 ひかる
  nickname: ホノカ
  special_skill: 寝坊
  favorite_things: ['とんこつラーメン']
  belongs: ['高校生', '茶道部']
  unit: ['Le☆S☆Ca']
