madoka:
  id: 22
  idol_id: 22
  name:
    family: 榎並
    family_kana: エナミ
    given: マドカ
    given_kana: マドカ
    shorten: マドカ
  old: 13
  birthday: 9/4
  zodiac_signs: 乙女座
  blood_type: A型
  height: 136
  weight: 36
  bust: 72
  waist: 49
  hip: 75
  cv: 藤井 アユ美
  nickname: マドカ
  special_skill: ホルン…です
  favorite_things: ['犬とお散歩']
  belongs: ['中学生', '吹奏楽部']
  unit: ['七花少女']
