risyuri:
  id: 23
  idol_id: 23
  name:
    family: 前園
    family_kana: マエゾノ
    given: リシュリ
    given_kana: リシュリ
    shorten: リシュリ
  old: 17
  birthday: 9/26
  zodiac_signs: てんびん座
  blood_type: B型
  height: 155
  weight: 44
  bust: 76
  waist: 53
  hip: 78
  cv: ルゥ・ティン
  nickname: リシュリ
  special_skill: 服つくり〜
  favorite_things: ['えりんぎのお味噌汁〜']
  belongs: ['高校生', '衣服同好会']
  unit: ['七花少女']
