romanofusuki:
  id: 25
  idol_id: 25
  name:
    family: ターシャ
    family_kana: ターシャ
    given: ロマノフスキー
    given_kana: ロマノフスキー
    shorten: ロマノフスキー
  old: 12
  birthday: 11/15
  zodiac_signs: 蠍座
  blood_type: AB型
  height: 138
  weight: 35
  bust: 72
  waist: 50
  hip: 73
  cv: 高岸 美里亜
  nickname: ターシャ
  special_skill: 賛美歌合唱
  favorite_things: ['雪とオレンジの街灯']
  belongs: ['留学生']
  unit: nil
