sawori:
  id: 27
  idol_id: 27
  name:
    family: 夜舞
    family_kana: ヨマイ
    given: サヲリ
    given_kana: サヲリ
    shorten: サヲリ
  old: 14
  birthday: 10/29
  zodiac_signs: 蠍座
  blood_type: A型
  height: 157
  weight: 45
  bust: 79
  waist: 56
  hip: 77
  cv: 稲川 英里
  nickname: サヲリ
  special_skill: 傷の治りがすっごく早い
  favorite_things: ['バスに乗ること']
  belongs: ['中学生']
  unit: ['七花少女']
