monaka:
  id: 28
  idol_id: 28
  name:
    family: 雲巻
    family_kana: クモマキ
    given: モナカ
    given_kana: モナカ
    shorten: モナカ
  old: 17
  birthday: 5/4
  zodiac_signs: 牡牛座
  blood_type: O
  height: 152
  weight: 41
  bust: 73
  waist: 54
  hip: 77
  cv: 桜木 アミサ
  nickname: モナ
  special_skill: とくになしー
  favorite_things: ['ショッピング']
  belongs: ['フリーター']
  unit: ['七花少女']

