matsuri:
  id: 30
  idol_id: 30
  name:
    family: 三森
    family_kana: ミモリ
    given: マツリ
    given_kana: マツリ
    shorten: マツリ
  old: 21
  birthday: 10/9
  zodiac_signs: てんびん座
  blood_type: O型
  height: 151
  weight: 38
  bust: 72
  waist: 53
  hip: 76
  cv: 巽 悠衣子
  nickname: マツリ
  special_skill: ゲームならなんでも
  favorite_things: ['メダル集め']
  belongs: ['フリーター']
  unit: ['The QUEEN of PURPLE']
