manon:
  id: 34
  idol_id: 34
  name:
    family: 星柿
    family_kana: ホシガキ
    given: マノン
    given_kana: マノン
    shorten: マノン
  old: 8
  birthday: 11/9
  zodiac_signs: 蠍座
  blood_type: O型
  height: 133
  weight: 31
  bust: 65
  waist: 47
  hip: 60
  cv: 山岡 ゆり
  nickname: マノン
  special_skill: 魔法
  favorite_things: アニメを見ること
  belongs: 小学生
  unit: -
