murasaki:
  id: 36
  idol_id: 36
  name:
    family: 越前
    family_kana: エチゼン
    given: ムラサキ
    given_kana: ムラサキ
    shorten: ムラサキ
  old: 18
  birthday: 10/1
  zodiac_signs: てんびん座
  blood_type: A型
  height: 161
  weight: 48
  bust: 87
  waist: 52
  hip: 76
  cv: 野村 麻衣子
  nickname: ムラサキ
  special_skill: ジャズボーカル
  favorite_things: ['ペディキュア']
  belongs: ['高校生']
  unit: ['The QUEEN of PURPLE']
