nikoru:
  id: 40
  idol_id: 40
  name:
    family: 七咲
    family_kana: ナナサキ
    given: ニコル
    given_kana: ニコル
    shorten: ニコル
  old: 17(2032年時)
  birthday: 7/7
  zodiac_signs: 蟹座
  blood_type: O型
  height: 159
  weight: 44
  bust: 84
  waist: 55
  hip: 77
  cv: 水瀬 いのり
  nickname: ニコ
  special_skill: 好きな夢を自由に見れる
  favorite_things: ['友だち', 'ドーナツ']
  belongs: ['セブンスシスターズ']
  unit: ['セブンスシスターズ']
