mito:
  id: 41
  idol_id: 41
  name:
    family: 羽生田
    family_kana: ハニュウダ
    given: ミト
    given_kana: ミト
    shorten: ミト
  old: 17(2032年時)
  birthday: 10/31
  zodiac_signs: 蠍座
  blood_type: A型
  height: 158
  weight: 43
  bust: 80
  waist: 55
  hip: 76
  cv: 渕上 舞
  nickname: ミト、ハミィ閣下
  special_skill: 歌
  favorite_things: ['歌', '豆腐']
  belongs: ['セブンスシスターズ']
  unit: ['セブンスシスターズ']
