kuruto:
  id: 43
  idol_id: 43
  name:
    family: 寿
    family_kana: コトブキ
    given: クルト
    given_kana: クルト
    shorten: クルト
  old: 14(2032年時)
  birthday: 12/4
  zodiac_signs: 射手座
  blood_type: O型
  height: 156
  weight: 45
  bust: 83
  waist: 57
  hip: 78
  cv: 黒瀬 ゆうこ
  nickname: クルト
  special_skill: クルトキックだぞ！
  favorite_things: ['トランポリン']
  belongs: ['セブンスシスターズ']
  unit: ['セブンスシスターズ']
