rui:
  id: 44
  idol_id: 44
  name:
    family: 若王子
    family_kana: ワカオウジ
    given: ルイ
    given_kana: ルイ
    shorten: ルイ
  old: 18(2032年時)
  birthday: 1/6
  zodiac_signs: 山羊座
  blood_type: A型
  height: 171
  weight: 51
  bust: 83
  waist: 54
  hip: 78
  cv: 川﨑 芽衣子
  nickname: ルイ、ルイ王子
  special_skill: ロードレーサー
  favorite_things: ['こたつとみかん　だな☆']
  belongs: ['セブンスシスターズ']
  unit: ['セブンスシスターズ']
