memoru:
  id: 45
  idol_id: 45
  name:
    family: 遊佐
    family_kana: ユサ
    given: メモル
    given_kana: メモル
    shorten: メモル
  old: 16(2032年時)
  birthday: 3/3
  zodiac_signs: 魚座
  blood_type: AB型
  height: 140
  weight: 36
  bust: 76
  waist: 50
  hip: 80
  cv: 辻 あゆみ
  nickname: メモル
  special_skill: お料理なの♪
  favorite_things: ['ファンのみんなだよぉ♪']
  belongs: ['セブンスシスターズ']
  unit: ['セブンスシスターズ']
